name: Aggiorna Link Rai
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

permissions:
  contents: write

jobs:
  update-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installa Motore
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Estrai Video
        run: |
          LINK=$(yt-dlp -g --playlist-items 1 https://www.rainews.it/tgr/toscana/notiziari)
          echo "#EXTM3U" > miaplay.m3u
          echo "#EXTINF:-1 tvg-logo=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtfeAtVG3N5k7LYqcClHQGVXchhfWFu1dr7Q&s", TGR Toscana HD" >> miaplay.m3u
          echo "$LINK" >> miaplay.m3u

      - name: Salva Risultato
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git add miaplay.m3u
          git commit -m "Aggiunto logo definitivo" || exit 0
          git push
