name: Aggiorna Lista

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Aggiorna TGR Toscana
        run: |
          echo "#EXTM3U" > list.m3u
          echo "#EXTINF:-1 tvg-logo=\"https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTtfeAtVG3N5k7LYqcClHQGVXchhfWFu1dr7Q&s\", TGR Toscana HD" >> list.m3u
          echo "https://vod8-rai-it.akamaized.net/podcastcdn/TG_regionali/TG_Toscana/28245325.mp4/chunklist_b1758000_t64MTgwMA==.m3u8" >> list.m3u

      - name: Git Config
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add list.m3u
          git commit -m "Aggiornato link TGR Toscana" || echo "Nessuna modifica"
          git push






