name: Aggiorna Link Rai
on:
  workflow_dispatch:
  schedule:
    - cron: '0 * * * *'

jobs:
  update-link:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Installa yt-dlp
        run: |
          sudo curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp -o /usr/local/bin/yt-dlp
          sudo chmod a+rx /usr/local/bin/yt-dlp

      - name: Estrai Video
        run: |
          LINK=$(yt-dlp -g --playlist-items 1 https://www.rainews.it/tgr/toscana/notiziari)
          echo "#EXTM3U" > miaplay.m3u
          echo "#EXTINF:-1 tvg-logo=\"https://www.rai.it/dl/img/2020/01/24/1579882255850_TGR_Toscana.png\", TGR Toscana HD" >> miaplay.m3u
          echo "$LINK" >> miaplay.m3u

      - name: Salva Risultato
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add miaplay.m3u
          git commit -m "Aggiornamento automatico" || exit 0
          git push
